---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Enable UFW
  ufw:
    state: enabled

- name: Setup UFW rules
  ufw:
    rule: "{{ item.rule }}"
    name: "{{ item.name }}"
  loop: "{{ ufw_rules }}"
